"""Initials

Revision ID: c859a71497c1
Revises: 8c8d67666bb2
Create Date: 2025-05-12 20:04:39.353130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c859a71497c1'
down_revision = '8c8d67666bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_purchasable', sa.Boolean(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Goods', 'Services', 'Info', name='category', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('Goods', 'Services', 'Info', name='category', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('is_purchasable')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
